### ISSUE TITLE
fixate/reporting/csv.py Uses optional data to make directory structure

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#11]
Currently, the csv file assumes that part_number and module are parsed to the program launch through --script-params.

Need to change so that the folder structure of the csv logs are able to be configured through a configuration file.

https://github.com/PyFixate/Fixate/blob/bb816960280feea263288c898ca360fbf4b7f34f/src/fixate/reporting/csv.py#L115-L122

**Comment by pazzarpj** [comment]
Also
https://github.com/PyFixate/Fixate/blob/bb816960280feea263288c898ca360fbf4b7f34f/src/fixate/__main__.py#L268-L275

**Comment by clint-lawrence** [comment]
For now we could default to cwd and a timestamp (or timestamp-scripname) for the log. That would be a sensible default when testing/debugging scripts without requiring too many additional config hooks just yet
