### ISSUE TITLE
Move the log to a better location

### ISSUE THREAD

**Issue by clint-lawrence** [PyFixate/Fixate#128]
The python logs are currently written to the current working directory. This should change to a better default location (appdirs.site_data_dir("Fixate") or appdirs.user_log_dir("Fixate")) Also, we would ideally add some configuration for the logging. If nothing else, a command line parameter to set the log directly.

**Comment by jcollins1983** [comment]
@clint-lawrence , @John2202W's changes that were merged under PR #158 address the log location. Did you want to keep this issue open for the last 2 sentences?
Did you have any particular configuration in mind? The command line parameter is easy enough.

**Comment by clint-lawrence** [comment]
We should at least check the tests to ensure they aren't dumping a bunch of logs to outside of the test folder when running locally. (similar to the issue @John2202W is fixing with https://github.com/PyFixate/Fixate/pull/160). We can possible do that by adding the the --disable-logs flag to the script2log tests.

**Comment by John2202W** [comment]
Good point, have disabled the logs in #160

**Comment by John2202W** [comment]
Do we still want a command line arg to set the name/location of the fixate.log 's ?

**Comment by clint-lawrence** [comment]
Unless you're keen, I'd say just leave it until we have the need.

**Comment by clint-lawrence** [comment]
fixed in #203 and #155
