### ISSUE TITLE
Make it possible to run the command line ui non-interactively

### ISSUE THREAD

**Issue by clint-lawrence** [PyFixate/Fixate#14]
This is initially motivated by wanting to write a few simply integration tests. In particular, I was intending to write some tests that run a simple script (that might pass, fail or error) and then check the process return code and check the generated log file.

This is complicated by the fact that the script runs assuming there will be user interaction. Of course, this makes sense in our typical deployment, but if we can decouple some of those behavioural aspects from the core logic, it will be easier to test certain parts of the code.

**Comment by pazzarpj** [comment]
Agree, the final user_ok at the end of execution was to provide visual feedback to the user whether it was successful or not.
The current way we have it deployed means that the return codes created from finishing the execution are more important. 
If demand warrants the information to persist after execution, this could be added as a command line option.
