### ISSUE TITLE
GUI doesn't print user_info steps

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#15]
The GUI should print user_info to the Active window until the next user blocking call.

For eg.
```python
user_info("Hello")
user_info("World")
user_ok("You got that?")
```
Currently displays
You got that?

When it should display
Hello
World
You got that?

**Comment by pazzarpj** [comment]
I think the appropriate behaviour should show the commands in the active window until a test is completed or a blocking user call like user_ok or user_choices are made.
This behaviour should probably also be mimicked with the user_image and user_image_overlay.

**Comment by pazzarpj** [comment]
Latest version doesn't seem to do as promised

**Comment by pazzarpj** [comment]
I suspect this regressed with the refactor in #31

**Comment by clint-lawrence** [comment]
This is working now.
