### ISSUE TITLE
Aborting on GUI causes lock up

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#47]
When clicking abort, the Aborting message is incorrect causing the messaging library to lock up.

`  File "C:\dev\Github\Fixate\src\fixate\ui_gui_qt\ui_gui_qt.py", line 411, in update_tree
    self.active_update(message="Aborting, please wait...")
TypeError: active_update() missing 1 required positional argument: 'msg'`

**Comment by clint-lawrence** [comment]
PR is merged, so closing this issue
