### ISSUE TITLE
GUI sometimes hangs after finishing test

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#49]
Noticed that all testing is finished but GUI hangs on the AutoAuto V10 test scripts.
Investigate this in relation to things such as Test List exit and sequencer and anything else that might be holding the sequencer hostage.

**Comment by pazzarpj** [comment]
Could have something to do with #54

**Comment by clint-lawrence** [comment]
Yes, related to #54. Will be fixed when #108 gets merged.
