### ISSUE TITLE
User action doesn't allow you to pass on GUI

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#50]
User action on cmd_line says space for pass and escape for fail.
GUI needs a pass fail button for the user_action

**Comment by clint-lawrence** [comment]
With #108, the cmd_line actually changed, so space no longer forces a pass. (and the prompt was change accordingly).

I don't think this is a problem anywhere it has been used to date, and seemed to be a more consistent with the concept of the user_action call. So, closing this now essentially as a won't fix. Happy to re-introduce that capability in the future if a need arises.
