### ISSUE TITLE
Python crashes

### ISSUE THREAD

**Issue by pazzarpj** [PyFixate/Fixate#60]
Ben is reporting that with 0.4.3, the gui in dev mode is unreliable and causing the entire process to crash on windows.

**Comment by pazzarpj** [comment]
0.4.2 had the same issue.
#51. This seems to be a computer setup with a combination of corrupted installations of QT, python and ftdi dlls.
Leaving open until fresh install shows if this issue is resolved

**Comment by clint-lawrence** [comment]
And possibly related crashes seen while testing with the GUI in dev mode on the 'spare' jig PC.

**Comment by clint-lawrence** [comment]
GUI has been pretty reliable on 0.5.3 for over 12 months now.
